source 'https://rubygems.org'

gem 'dashing', git: 'https://github.com/warnergodfrey/dashing.git', branch: 'update-rufus'

## Remove this if you don't need a twitter widget.
gem 'twitter', '>= 5.9.0'
